### ISSUE TITLE
Mass Check

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#1004]
With the latest player_login.fsm the issue is still occurring:

`11:20:44 "DEBUG: Checking Player Object: OK"
11:20:44 "DEBUG: Checking Player PosVar: OK"
11:20:44 "DEBUG: Final Player mass check: FAILED (770 != 769.63)"`

Think I will just remove the check completely (again)

**Comment by Ignatz-HeMan** [comment]
thx for the feedback.
(770 != 769.63) is more than expected (and handled by the fix).
I would not completely remove the check, because Players could spawn without any gear then.
You notice this issue often? Then you could try a fix from @82ndab-Bravo17 :
This give much more tolerance and should work in this case!

`_playerCheckMass = ((abs(_loadabs - (loadabs _playerObject))) < 1);`

Some feedback would be great. Then we could official change it.

**Comment by 82ndab-Bravo17** [comment]
Is the character permanently broken, or can they log in if they try again?

Also, could you ask some players on your server to check their .rpt files after they log in OK and see if the first value for the mass is ever a non-integer?

**Comment by morgoth0** [comment]
Black screen, authentication failed (with the pubvar timeout kick) every time. Been having this problem on and off for a long time now - think I first reported it. AWOL suggested a distance thing (murkily remembering a conversation) and it does seem to be a thing... only happens on large maps where the spawn chamber is not centred and the player is very far away from it... Will go through my old unorganized handwritten notes for more info.

Always has that mass check error. Not common, less common since He-Man implemented the setunitloadout stuff but still happens. Problem is that when it happens the only solution is to delete the player record in REDIS... would not mind that, never used to be any issue (apart from comping people) until someone moved effing group info into the player record - which, IMO, was a bad decision

**Comment by Ignatz-HeMan** [comment]
The distance should no longer be a problem, because we have completely changed the script.
1. Ghost spawn in spawn chamber
2. New unit also spawn in spawn chamber
3. New unit get unit loadout
########## Here is your stuck ##############
4. client tell the server, that loadout is okay
5. Server move the new unit to his final destination
6. Client switch into new unit.

But... I wonder about the difference of (770 != 769.63). Arma / Epoch do not have any items with a mass smaller than "1". So I am pretty sure it have to do with a custom mod.
So I would suggest to test the above check from @82ndab-Bravo17. It will give you much more tolerance, but also should prevent nacket spawning Players.

**Comment by morgoth0** [comment]
Will do so tomorrow He-Man. I will let you know whether the issue reoccurs. Unfortunately it is just a case of wait and see because it is fairly rare

**Comment by 82ndab-Bravo17** [comment]
You could probably just delete the players loadout rather than the whole player record, which would leave  the group info intact.

What mods do you have installed/allow on server?

**Comment by morgoth0** [comment]
Does deleting the loadout fix it... that would be good. Will check if it happens after implementing your code.

Mods on this server (doesn't really matter because I've had it on every server run - but rare for sure): 

CBA_A3, CUP Terrains - Core, CUP Units, CUP Vehicles, CUP Weapons, Enhanced Movement, Epoch, Extended Base Objects For Epoch, Hellenic Armed Forces Mod (HAFM), Immersion Cigs, KA Weapons Pack NEW, NIArms All in One, RDS Civilian Pack, WW2_units_mas, Zombies and Demons

**Comment by morgoth0** [comment]
Probably will be removing RDS Civilian Pack from my servers now that the issues with some of the civ Cherno uniforms in CUP have been fixed and they added the Zetor tractor. CUP is still missing the Jawa bike but fewer mods are good and I cannot see myself keeping it just for one motorbike - especially since the TT650 is my ride of choice :)

**Comment by Ignatz-HeMan** [comment]
Shoule be now finally fixed by @82ndab-Bravo17:
https://github.com/EpochModTeam/Epoch/commit/21c7adaf78501190140edb2731123ef03fd7fa77
