### ISSUE TITLE
Enemy not shooting

### ISSUE THREAD

**Issue by SamuelLiasam** [EpochModTeam/Epoch#1016]
Hi everyone. Whenever I play a game in Arma 3 I always have the issue that the enemy which is often Independent doesn't attack me. Myself (BLUEFOR) engages at the enemy and does what it needs to do. However, the enemy doesn't fire back and I am literally able to shoot the enemy from a close distance without resistance. Also in the game independent is set as the enemy so that makes it even weirder.
Does anyone know how to fix this?

**Comment by morgoth0** [comment]
Obviously this is not really an Epoch issue since Epoch's AI behave properly. I assume you mean in scenarios you are setting up. If so, in Eden you need to bring up the Attributes>General Window. Note the Independents Allegiance section. By default BLUFOR are friendly with GUER so click on the blue icon to make them hostile
![20200826125109_1](https://user-images.githubusercontent.com/16226987/91333080-18c91580-e79b-11ea-9ddc-0f8bb2551dbb.jpg)

**Comment by SamuelLiasam** [comment]
I have GUER on hostile also I always click the blue button to make them hostile. They still, however, don't engage at me whenever I am BLUEFOR or OPFOR

**Comment by Ignatz-HeMan** [comment]
As this git is for A3 EpochMod only, I will close this issue now.
But you could discuss this within the A3 Discord: https://discord.gg/arma
