### ISSUE TITLE
[suggestion] Passive Base defences

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#172]
-Eletric fence for the base.
(perhaps also as an upgrade to add it to the walls.)

- Barbed wire fence for the base.
(perhaps also as an upgrade to add it to the walls.)

**Comment by ZNUfisk** [comment]
How about instead of maintaining the FJ for krypto, you have to plug batteries in it, and depending on how many passive defenses you add, the more often the battery needs to be replaced. Features like:

* Electric mines (that persist after restart)
* Electric barrier (like a 5m force field around the jammer)
* Electric locks (battery goes out, all the biometric locks unlock)
* Electric alarm system with perimeter detection (if someone not in group steps inside perimeter, alarm goes off (attracts attention of antagonists))
* Floor plates that have current running through them

**Comment by nerdalertdk** [comment]
would lead to some fun base rads :dancer:

**Comment by vbawol** [comment]
Thanks for the feedback guys, we will be adding more stuff like this in the next few patches. 0.3.5 will bring a persistent spike trap that you can set around your base.
