### ISSUE TITLE
Sharks ain't very agressive

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#178]
Should think a shark would attack of you jumped in to the water and on to his head. ;) : http://youtu.be/ppPsIyAe5Dk

**Comment by andgregor** [comment]
They are currently quite passive, update soon, along with better water depth detection.

**Comment by Pmba79** [comment]
Cool.. How about the sharks hitbox ?
Seems somewhat off..
I shot 2 mags from the Sdar with no effect..
(mainly shot from below up in the belly)

2015-02-22 13:41 GMT+01:00 Andrew Gregory <notifications@github.com>:

**Comment by vbawol** [comment]
Note: @andgregor I think the use of setVelocityTransformation could do wonders for the sharks ability to turn and change elevation.

@Pmba79 there is a "bite" attack animation for the sharks and should only seen when the shark attacks. part of the problem is he rarely ever gets close enough to attack.

**Comment by vbawol** [comment]
tracking here: https://github.com/EpochModTeam/Epoch/issues/583
