### ISSUE TITLE
[Suggestion] Group size affects jammer building parts allowed

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#241]
ie. a larger group will allow for more building pieces. - a group of 2 players having the same build limit as a group of 16 makes little sense.

**Comment by Pmba79** [comment]
Don't agree at all..
That way people who "lone wolf" or only play with a few friends will be nerfed..

**Comment by ZNUfisk** [comment]
Not really. 

You just scale the build limit up from a certain amount (eg. 200).

**Comment by Skaronator** [comment]
The issue is arma.
We would like to make an upgrade system for Jammer as well but that wouldn't help the server at all. We have just added the building limit to lower down the buildings on the server due the limitation on arma side. Maybe is it possible to bug @Dwarden to improve the createVehicle handling on server in arma.

**Comment by vbawol** [comment]
added in b563
