### ISSUE TITLE
[Improvement] Vehicle spawning system

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#255]
Current behaviour:

Vehicle pool is based on total vehicles defined in the epochconfig-array, once all vehicles have spawned on the server the vehicle pool is considered full, and no new vehicles will be spawned. Vehicles sold will not change this. Vehicles that are in the trader inventory ALSO count toward the total number.

Suggested behaviour:

Vehicle pool is based on total vehicles that are actually on the map. Vehicles on the map spawn in a broken/unfueled or semi-broken state (configurable). Traders will only purchase a fully repaired, and at least 90% fueled. If a vehicle is purchased that spills over the total max, a random vehicle from the same pool is despawned (making it so there's ALWAYS a certain max). 

Explanation:

There should ALWAYS be the same (defined) amount of vehicles on the map. The ability to find vehicles have a direct effect on player interest, especially on larger maps (such as Altis). This system makes it so to sell (and make money from) a vehicle you have to put in effort to repair, refuel and drive it to a trader. This spends resources, and the new spawned vehicle will be broken and need repairs/refuels. That way we aren't causing so much resource inflation. We also keep the same amount of vehicles on the map. This also encourages players to purchase vehicles, as the vehicles in the traders will be repaired/fueled.

**Comment by Sephyr** [comment]
Having a switch to allow for trader inventory check would be very nice.
Ive seen numerous occasions of player based "death squads" roaming the map and killing every trader that has a vehicle in their inventory.

An issue i could see arise with above suggestion is; the despawning of said vehicles could be player-owned and inside a base. 
I imagine this could be circumvented with a check on last updated vehicles of sorts, removing the oldest vehicle of purchased classname that is on the map, but even this might not entirely be ideal.
Possibly have it allow for a buffer of purchased vehicles during uptime (amount configurable) and said buffer/vehicle list could be cleared up on the map/DB on restart?

A more drastic way could be to allow server owners to choose wether or not to wipe certain categories (vehicles in this case) from trader inventories on restart to repopulate the map.

Hope my input helps and if anything would be complimentary to OP

**Comment by DarthRogue** [comment]
I think it should work like this: When the server restarts it should load ALL vehicles in the vehicles table, regardless of the max limit specified in the epochConfig.  If a vehicle is in the vehicle table, that means it was either spawned in by the server on a previous restart or was purchased by a player from a trader.  Either scenario means that the vehicle is supposed to be there.  Vehicles that reside in trader inventories should NOT count towards the overall vehicle total on the server.  If the quantity of a particular vehicle class is under the limit specified in the epochConfig, THEN the server can spawn more of that class and place them at random around the server, but that should be the only time the epochConfig is consulted for vehicle spawning limits.  

Another option is that you could add a "Last Accessed" field to the vehicle table which would contain a date and time stamp of the last time a person interacted with that vehicle.  If the time is over 'X' days then the vehicle can be passed over for spawning in preference of other, more frequently used vehicles.  Then you could also say that any vehicles over "x"  additional days since last access by a player can be deleted and replaced with a fresh one on the following restart.

**Comment by vbawol** [comment]
ref 
#221 Traders spawn vehicles right on top of themselves

**Comment by vbawol** [comment]
You can now control the total max vehicles that can be saved on the traders. This system should also prefer to keep vehicles on the main static traders first. This in effect does what you ask here in that if your max vehicle limit is 156 and the stored vehicle limit is 20 you should always end up with 136 on the map.

Also all vehicles now spawn with a random fuel level even if purchased from a trader. The next step would be to add random damage to world spawned vehicles.
