### ISSUE TITLE
[Suggestion] Ability to restrict frequency jammer numbers owned by the same group

### ISSUE THREAD

**Issue by MGTDB** [EpochModTeam/Epoch#287]
I propose that a limit can be put on the amount of frequency jammers that can be owned per group. Maybe make the amount a variable set by server admins. 

This would stop large(r) established groups creating too many frequency jammed bases thus making it harder for newer players to get established.

**Comment by donkeypunchepoch** [comment]
I agree group based limit would counteract those issues.
however a new set of players without a group could exploit that and setup multiples then create the group to bypass this.

This should be two config settings, one for player and one for group.
however,

Then you run into the problem of adding a new individual who already has a base within the limits but then can't join the group because it would put them over the limit or it would just bypass the setting anyways, leading us back down the same road as we started with.

**Comment by MGTDB** [comment]
Then maybe if a new set of players exploit that with multiple jammers they get locked out of creating a group?

**Comment by bacchus101** [comment]
In conjunction with a configurable and/or much higher per peice default maintenance cost, I think a group + per user frequency jammer limit would be a major step forward in keeping the world limit in check on high population servers.

**Comment by MatijsVDG** [comment]
Would love to see this.

**Comment by Oshydaka** [comment]
+1

Maybe add it confirgurable on epochconfig.hpp with a variable like 

"jammer_number_per_group" and set it to 0 or -1 to no restriction, and then like 1 / 2 / 3 / .... like admins wants !

**Comment by vbawol** [comment]
Thanks to @Ignatz-HeMan this has been added since b563
