### ISSUE TITLE
Major FPS drop with either 0.3.0.4 and/or Arma 3 update 1.48

### ISSUE THREAD

**Issue by moosemilker** [EpochModTeam/Epoch#328]
Players are reporting major FPS drop with Epoch version 0.3.0.4 and/or Arma 3 update 1.48.

To reproduce, just play the game on any server running Epoch 0.3.0.4 and Arma 3 version 1.48.  FPS can be high/normal for a while, but FPS will be somewhere around 15-20 FPS lower than normal, and then they bounce back up, then down, up, down, up, down... etc.  At one point, after playing for hours, I hit a 6 FPS wall and could no longer play.  I had to log out.  I logged out to the lobby, then came back into the game to normal higher FPS.  Players keep asking me if the server is about to crash, although the issue appears like a client-side issue... Though who knows! :) 

Epoch forum thread here: http://epochmod.com/forum/index.php?/topic/36504-0304-build-1-are-you-seeing-this/

**Comment by wismerheal** [comment]
It's related to this innit ?
If so, you've got a workaround proposed by BIS (RC hotfix MP stable compatible)

**Comment by donkeypunchepoch** [comment]
Lol won't fix label....

The issues you are seeing started with arma update 1.46
memory leaks , client crashes, fps drops on both client and Server. ....

Bis would  otherwise acknowledge it back in the second week of June.  They now released 1.48 the problems are still there and they are now saying they cannot recreate the issue in house, yet very server owner has complaints of their clients having these problems. 

Epoch did what they could during 0.3.0.3 to correct some of the issues that fell onto epoch with build 9, but with 0.3.0.4 and 1.48 those fixes were not needed, so now the problems left are bohemia s to fix.

Check vbawol posts about up voting feedback trackers and or check the main arma 3 feedback bug tracker and up vote those you feel relevant to this issue

**Comment by vbawol** [comment]
Marked "Wont Fix" because we are unable to do anything about this one. http://feedback.arma3.com/view.php?id=24852

**Comment by donkeypunchepoch** [comment]
Yes, I just never saw that tag before and thought it was funny! 
But I did mention Epoch did what they could during 0.3.0.3 to correct some of the issues that fell onto epoch with build 9, but with 0.3.0.4 and 1.48 those fixes were not needed, so now the problems left are bohemia s to fix.

**Comment by vbawol** [comment]
Arma released the hotfix, closing
