### ISSUE TITLE
Jammer should also maintain storage

### ISSUE THREAD

**Issue by Oshydaka** [EpochModTeam/Epoch#333]
Hi

I've notice that shelves don't seems to update their last "use" when you use the jammer to maintain the base and got cleaned...

So, i maintain with the jammer yesterday, and 3 shelves are missing today.

Is there a way to add shelves & storage thing to the maintain jammer effect ?

Maybe add it for admin can configure it, like

"storage_jammer_maintain" set to true or false

Thanks for reading

**Comment by donkeypunchepoch** [comment]
In the epoch config. Hpp you have 2 configurable options. 1 is storage objects and 1 is building objects.
this is where your issue comes in.plot poles only maintain building objects. Thus all storage objects must be interacted with on a weekly basis or however long your expiration is setup for.

It would be a nice idea but then if you have building restricted to plot poles, then you can't even place a lockbox or shelf or tipi without having a plot pole down, not everyone can achieve enough for a plotOle before needing a storage location first...

**Comment by Oshydaka** [comment]
Maybe there is a way to not count storage in the jammer building limit BUT update them with the maintain option if the admin set it that way ?

@vbawol is that possible to do that ?

**Comment by vbawol** [comment]
Ref
#251 Jammer maintenance not working right

This should be possible lets focus all feedback about storage maintenance here.

**Comment by Korwiin** [comment]
What "clock" determines the expiration time of structures/storage?  Is it the Epoch server uptime (in real world uptime, or in game accelerated time?), the redis DB uptime, or real world time stamps.   I am trying to figure out why items disappeared when a server was offline for >7 days... my expectation was that the server would pick right back up where it was last shut down... but many vehicles/structures/storage dissappeared.

**Comment by vbawol** [comment]
It is based on real world time so this would be why some items disappeared.

**Comment by vbawol** [comment]
added maintain of storage
