### ISSUE TITLE
Lots of vehicles spawning in one small area

### ISSUE THREAD

**Issue by 82ndab-Bravo17** [EpochModTeam/Epoch#352]
On Altis there is a point at 107106 on the road between the main island and the smaller almost island where lots of vehicles seem to spawn in a jumble. Today there were at least 5 cars, 2 trucks, 6 quads, 5 motorbikes and 1 gokart all in the one small area.

**Comment by briankgregory** [comment]
This is because you have too many vehicles in your spawn array for the map. EPOCH only has so many places to put vehicles and if you increase the numbers more then it can handle it starts dumping anything it can'f find an open spawn location for there. I had the same issue until I turned my limit numbers down in the vehicle array....

He may consider it a bug, but I thought I would let you know how to fix it if you want to.

**Comment by vbawol** [comment]
Vehicle spawning has been reworked recently, please let me now if you are still seeing this issue. PS it might take a server wipe or instanceID change to reset the existing vehicles .

**Comment by 82ndab-Bravo17** [comment]
A liberal supply of satchel charges alleviated the original problem , and it hasn't reappeared. I guess it only happened when there were lots of vehicles to be spawned.

Thank you
