### ISSUE TITLE
Trader Menu interaction issues [EXP Build]

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#407]
Trader Menu interaction issues

Submitter
Dan Dalsted

Date Seen
10/19/15

Versions
Current Exp Build as of 10/19/15

Bug Description
When interacting with a trader, on the trading screen pressing spacebar toggles the dropdown menu on and off repeatedly.  Also, the talk feature closes unless you hold spacebar down, which is counterintuitive to what some players will do imo

Severity

Minor

Steps to Reproduce
Approach a trader and interact with spacebar
Pay attention to how the menus work while holding spacebar, and also when you press spacebar and release after clicking on either menu.

Actual Behavior
Trading Menu has a flickering dropdown menu while holding spacebar
Talk Menu closes after you release spacebar

Expected Behavior
Trading Menu will open and not cause the dropdown menu to activate
Talk Menu will stay open after releasing spacebar

**Comment by raymix** [comment]
I'll see if I can re-introduce display back instead of dialog, seems to be causing a ton of issues simply because any top dialog can be closed with same exact command...
Displays however requires finding them before being able to close them... but there are other issues that comes with these guys... 

bis needs to get their shit together with UI code...

**Comment by orangesherbet** [comment]
Perhaps another way would be to have the 3D Tutorial text read "Hold Space" that way the menu would stay open?

**Comment by raymix** [comment]
No, it's not intended behaviour, this is in fact a bug, yes. I've already applied a workaround for similar dialogs, but I can only do so much before code starts getting ugly due to command limitations.
Originally dynamic action menu was based on display actually, I went with dialog because displays stacks.. which means you can have both action menu and gear menu open at the same time... probably not as bad as current situation.
I'll figure this one out over weekend, thanks for report, Dan

**Comment by orangesherbet** [comment]
I have full confidence in you, and myself and Poulmba will be doing further testing with interactions and report what we have on the github!
