### ISSUE TITLE
Duping of bipods (Pending: A3 command to manipulate weapons + attachments in cargo space)

### ISSUE THREAD

**Issue by 82ndab-Bravo17** [EpochModTeam/Epoch#411]
It seems that some weapons come with a bipod by default, but when they are saved to the db the bipod gets removed and placed in storage separately.

So on the next restart there is a bipod on the weapon by default, and also the bipod that was removed and stored separately.

**Comment by vbawol** [comment]
Ok so, I managed to handle one part of the duplication factor here. We now suppress saving of any attachments that are already a part of the weapon config. 

Problem is that you can still remove attachments from these weapons and they will regain there attachments again after restart.
- [ ] Every single weapon would need to have a config'ed version that is totally stripped down.

Pros: 
- can fix attachment dupe with converting all weapons into stripped down version.

Cons: 
- much more work to maintain and config.
- Attachments end up in the cargo inventory and have to be put back on the weapon manually. (Current Behavior)
- not all weapons can be supported in this way, only A3 and epoch ones not CUP, etc. as each one would need to be setup manually via the Epoch mod client configs.

Or 
- [x] Plead with BI to add a way to manipulate weapons + attachments on spawning into a cargo space.

Pros: 
- Can fix attachment dupes given better control over weapon attachments and will result in greater performance due to less code.

Cons: 
- May not get feature for some time or not at all.

**Comment by vbawol** [comment]
https://feedback.bistudio.com/T82178 - Bipod Duplicating

Some other BI feedback threads that people are asking BI to add a way to manipulate weapons + attachments on spawning into a cargo space:

https://feedback.bistudio.com/T63270 - Expand weapon holder container manipulation commands to be able to add and get weapons with accessories

https://feedback.bistudio.com/T80047 - No commands to add a weapon to cargo with custom attachments

https://feedback.bistudio.com/T80358 - Add/Alter script command to add perfectly configured weapons to cargo

**Comment by Vampurica** [comment]
Can we add removeAllPrimaryWeaponItems/removeAllHandgunItems/{ removeSecondaryWeaponItem _x; } forEach ( secondaryWeaponItems player) on the player creation to prevent the duplication?

https://community.bistudio.com/wiki/removeAllPrimaryWeaponItems
https://community.bistudio.com/wiki/removeAllHandgunItems
https://community.bistudio.com/wiki/removeSecondaryWeaponItem
https://community.bistudio.com/wiki/secondaryWeaponItems

May also be required when trading if that is also an issue.

EDIT: Is bipod duplication still an issue? It should be working as intended according to the code:
https://github.com/EpochModTeam/Epoch/blob/e16ee710ae7cd909fa4f9b1eae569a182e8cc10d/Sources/epoch_server/compile/epoch_player/EPOCH_server_loadPlayer.sqf#L244

Maybe we need to waitUntil the game recognizes the weapon is added before removing attachments?

**Comment by Vampurica** [comment]
I believe all of the weapon item commands require being executed local to the client. Not sure where they need to be moved too, but that is likely the reason why this bug exists.

They are currently running on the server side therefore throwing no errors yet doing nothing.

**Comment by vbawol** [comment]
It happens when you remove a bipod from a weapon then store it in a vehicle or storage. As there is no way to manipulate the attachments when working with cargo space.

**Comment by vbawol** [comment]
Since bipods can be duped, I suggest they have no value at traders. https://github.com/EpochModTeam/Epoch/commit/662ef386b1c5c36b082b489ccaf803f18e8ad4c7

If Bi adds a way to manipulate the attachments in cargo space, we can just reset pricing.
