### ISSUE TITLE
Duping of Torso Items

### ISSUE THREAD

**Issue by XuanWuUnlimited** [EpochModTeam/Epoch#413]
While testing different body armors for damage mitigation it was found that the bodies of the deceased player would flicker and duplicate the armor they were wearing prior to dying for a brief period of time (30-45 seconds). It was not a complete duplication at this time though; the item is duplicated but the inventory is shared across all of the duplicated chest pieces (phantom item).  This was tested with 3 different chest pieces with consistent results. Backpacks are also duplicated on the bodies but are unlootable.  It was futher tested by selling the chest pieces to the vendor, which was successful.  And upon server restart when the item was purchased back from the vendor, it became a completely duplicated item no longer sharing the inventory across all phantom items.

**Comment by vbawol** [comment]
This sounds like it might be a Arma engine bug, we did have a check for duplicate uniforms, vests, and backpacks however a recent Arma patch broke its ability to work so we had to remove it. I was under the impression that this was no longer an issue because of that but apparently not. 

Ideally we need to reproduce this in a standard Arma 3 mission and then BI will be able to reproduce the issue and fix it faster.
