### ISSUE TITLE
Trader Menu issues (requires energy?) [EXP Build]

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#415]
Trader Menu interaction issues

Submitter
Dan Dalsted

Date Seen
10/31/15

Versions
Current Exp Build as of 10/31/15

Bug Description
When interacting with a trader, attempting to sell items gives the message "need energy"
Attempting to trade when you have energy results in no message, no script error
Severity

Major

Steps to Reproduce
Approach a trader and interact with spacebar
Put items in the queue to sell
Click sell

Actual Behavior
Gives the message "need energy" when you click sell
Gives no feedback when the player has energy when selling

Expected Behavior
Items sell normally with the message "items sold" when the transaction is complete

**Comment by raymix** [comment]
Fixed in my branch

**Comment by SirDice** [comment]
I've been unable to sell anything to a trader, with or without energy. As of build 026 the "need energy" message is gone but when you click on the Trade button nothing happens.

**Comment by raymix** [comment]
The original report did not have issues with trading that you are having, @SirDice 
It was just a "need energy" message that happened when it shouldn't and was tied as a bug to the new action menu only.
What you are experiencing now is something else, because after trader dialog is created successfully without any odd messages, this bug becomes solved.

This just means we have to look elsewhere for the solution - starting with function launched by trade button.

This is happening on experimental, right?

**Comment by SirDice** [comment]
>This is happening on experimental, right?
Yes.
>Could you open a new issue instead and be as descriptive as possible please, it would help us a >great deal to reproduce the steps and experience it ourselves. Thanks
I will. Thanks.
