### ISSUE TITLE
Error Type Display (dialog), expected String Since A3 1.54

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#433]
http://epochmod.com/forum/index.php?/topic/40285-epoch-035053-and-armaupdate-154/ 

Confirmed error while targeting a vehicle for interaction
```
13:57:58 Error in expression <icMenu.sqf"
disableSerialization;
_in = param [0, "", [""]];
_display = findDisp>
13:57:58   Error position: <param [0, "", [""]];
_display = findDisp>
13:57:58   Error Type Display (dialog), expected String
13:57:58 File x\addons\a3_epoch_code\gui\scripts\dynamenu\EPOCH_dynamicMenu.sqf, line 2
```

**Comment by raymix** [comment]
Looks like param was updated (or they broke it)
_in should only receive string, nothing else.
Initially display from keydown is being sent, that's just how engine works, same thing that happens when buttons are pressed (ie debug on esc)

For some reason param lets display value true and does not convert it to "".

I'll try to find the time to fix this over the weekend

**Comment by raymix** [comment]
fixed using bis_fnc_param
