### ISSUE TITLE
kicks for remotexec.txt 

### ISSUE THREAD

**Issue by Ghostrider-DbD-** [EpochModTeam/Epoch#480]
Players are getting kicked for the following:

#0 "epoch_server_checkplayer C Alpha 1-1:1 REMOTE"

**Comment by vbawol** [comment]
did you update your remoteExec.txt?

**Comment by ScaRR-ZA** [comment]
I had the same, reason being that I didn't update the remoteExec.txt, Updating that fixed it.

**Comment by Ghostrider-DbD-** [comment]
Updating remoteExec.txt did the trick. Thank you both for the feedback.

**Comment by ReDBaroN1** [comment]
I have the updated filter and still get a kick every other day or so....

**Comment by vbawol** [comment]
This is likely due to the players name not being returned in some cases. I noticed this when testing 0.3.8 and the changes that bring back more BIS mp functionality such as the initPlayerServer.sqf however this still must be whitelisted in remoteExec configs..

Try this one:
https://raw.githubusercontent.com/EpochModTeam/Epoch/2afb4080a4e590b0d75e2e34aa4732af01bbe642/Server_Install_Pack/sc/battleye/remoteexec.txt

This change basically allows the player name to be empty.
```
!="epoch_server_checkplayer [A-Z]{1} [A-Za-z]{4,10} [0-9]{1,3}-[0-9]{1,3}:[0-9]{1,3}( \(.+\)|) REMOTE"
```
