### ISSUE TITLE
Epoch MEssages off the top of the screen - BE Filter

### ISSUE THREAD

**Issue by andgregor** [EpochModTeam/Epoch#534]
Experimental: on 1600x900 the new Epoch messages are off the top of the screen, if I spam the messages the 2nd or 3rd appears on the screen.

Also when going into OPtions > Game > Layout I received a BE kick #38 new working filter (if allowed) for line 40: `7 createDisplay !="createDisplay \"rmx_dynamenu\";" !="_parent createdisplay _displayClass;" !="finddisplay 151 createdisplay 'RscDisplayOptionsLayout'"`

**Comment by vbawol** [comment]
got the BE filter added.

**Comment by raymix** [comment]
Hard to say what's wrong since the script uses GUI_GRID for everything, it's the best way to deal with various resolutions IMO.
The line that causes this is [#L31](https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_code/gui/scripts/Epoch_dynamicText.sqf#L31) where -18 is hardcoded offset.
One of two things can be done - adjust this integer to fit smaller resolution and offsetting message lower for higher ones or come up with a new idea for messages, preferably at the bottom of the screen.

**Comment by raymix** [comment]
Message system revamped, so I'm closing this.
@vbawol this might require new BE filters, sorry :) But at least we can get rid off old ones.
