### ISSUE TITLE
Action Menu button bind is wrong

### ISSUE THREAD

**Issue by jostster** [EpochModTeam/Epoch#539]
The action button for both arma3 and epoch is set to space however to light a fire, open a door etc, I have to use the scroll wheel then press enter.

**Comment by vbawol** [comment]
I do know about this and experience the same thing. What key would you recommend we change it to?

**Comment by jostster** [comment]
would it be possible to keep both on space and have one be a long press and the default action be a quick press?

**Comment by vbawol** [comment]
Ideally yes, It was planned to work that way so we need to take another stab at it.

**Comment by raymix** [comment]
Dynamenu already has a 200ms delay added to it: [L91](https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_code/compile/interface_event_handlers/EPOCH_KeyDown.sqf#L91) for this exact purpose

However if you look at line 88, if cursorTarget is a vehicle class then action menu is instant. 
Both are intended effects.

For doors and such, don't press and hold to activate them, simply hit the spacebar, it should work.
Does not hurt to play around with increased delay, but keep in mind, anything too high might confuse people new to the menu

**Comment by vbawol** [comment]
@raymix the key is suppressed in the keydown function as it was causing triggering of the default actions. I cannot seem to find a command that can replicate what the Space key normally does but if we could activate that I think we could accomplish the use of both.

**Comment by raymix** [comment]
@vbawol I think spacebar is either hardcoded keymap or something you change in game's options. Not sure I am following you correctly on this one.
Epoch's keymaps saved in profile namespace are done here:
https://github.com/EpochModTeam/Epoch/blob/5e9860f4e94a8a25ddc823df5550b00a9952d2e3/Sources/epoch_code/compile/setup/EPOCH_clientKeyMap.sqf
Because of this function, Spacebar is used for actions by default. If you press RESET ALL on ESC menu, it reads that array and saves profile namespace.
Other than that, the current delay comes from epoch's keydown EH as said previously. The whole action menu is literary run by EPOCH_keysActionPressed boolean and calling epoch_dynamicMenu function. That's all there is to it. I'm not really following along what's the issue here, it works fine for me.

**Comment by raymix** [comment]
Ok I see what you mean now, something has changed recently as I was able to press space to open doors etc ... even long after dyna menu was created.
