### ISSUE TITLE
[BUG] Locking/unlocking of vehicles.

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#571]
Build Number: 0.3.9 - 562.

Server: Bulletbuffet - Tanoa. 

Bug Description: Able to unlock other players vehicles.

Severity: Minor.

Steps to Reproduce: Unlock another players vehicle right after he locked it.

Actual Behavior: The locking of the vehicle is open for unlocking for players not in the owners group.

Expected Behavior: The vehicle should not be possible to unlock for players not in the owners group.

Testing Steps Attempted: Tested it on 2 vehicles owned by different players not in group.

**Comment by vbawol** [comment]
Was anyone inside the vehicle at the time @Pmba79 ?

**Comment by Pmba79** [comment]
Negative

**Comment by Ignatz-HeMan** [comment]
Just tested it on our Server and I can not reproduce it.
The only changes in Lock / Unlock are:
- You can lock / unlock as crew member if the driver is dead
- You can lock / unlock as crew meber, if you are already the locked owner.
  Both have only effect, if you are INSIDE the vehicle.

We run exactly this code since about 3 Month on our Server, so I think it must be another "problem"

**Comment by Pmba79** [comment]
Wierd, We tried it multiple times with 2 different vehicles.
 I'll get someone to join me ingame and test it again..

**Comment by vbawol** [comment]
please reopen if this problem comes back.
