### ISSUE TITLE
loot positions on Altis have changed altitude.

### ISSUE THREAD

**Issue by waynewr1** [EpochModTeam/Epoch#588]
Seems like since the last patch that loot positions have changed altitude somehow.
chairs half buried in floors, blue tarp pallets only showing their top's  etc.

**Comment by OJohny** [comment]
Seen it also on Bornholm at some Arma3 Buildings.

**Comment by vbawol** [comment]
If you can get the classnames or screen shots it might speed things up. 

Also, this is the script I made to get these positions: https://github.com/EpochModTeam/Epoch/blob/release/Tools/SQF/saveLootPositionsVector.sqf 

Likely just need to reset them since it sounds like Bi changed the some of the building p3ds.

Note: If you load the epoch mission file in the editor then it should pull from the CfgBuildingLootPos class and populate the existing objects.

**Comment by waynewr1** [comment]
ok, i'll have a look this weekend. no experience doing this but hey gotta learn somehow :)

**Comment by waynewr1** [comment]
Could not get the CfgBuildingLootPos class to open in editor.
"Land_i_House_Small_03_V1_F" seems to be the one causing the issue.
I mucked around and put some objects in like the couch to see the difference in Pos.
Current epoch.altis couch pos "{ { -4.36719, -0.742188, -0.398075 }, 183.015 }" My pos "[["Couch_EPOCH",[11365.1,14242.9,0.83983],[[-0.524765,-0.851247,0],[0,0,1]]]

**Comment by baaljayjay** [comment]
in 0.3.0.9 In the windmill spawnt weapon case.
You can open it but you can not loot it.
![20161020234616_1](https://cloud.githubusercontent.com/assets/16623990/19581087/fafe9d64-972a-11e6-9285-fc8384152fb7.jpg)
![20161020234620_1](https://cloud.githubusercontent.com/assets/16623990/19581096/036a1424-972b-11e6-8854-7be6050bb9b3.jpg)

**Comment by vbawol** [comment]
These two have been fixed, please open another issue if this happens again. Since BI may update there models from time to time we may also have to update our positions.
