### ISSUE TITLE
Feature Request: store Krypto in safes, lockboxes or vehicles.

### ISSUE THREAD

**Issue by Ghostrider-DbD-** [EpochModTeam/Epoch#599]
A few players have asked about this and it seemed like a good idea to me.

**Comment by Ignatz-HeMan** [comment]
I think this will make atm's useless.
If you really want to store Krypto @ safes, you could just add:

class safe_epoch_p3d : bankTerminal {};
or
class safe_epoch: bankTerminal {};

to WorldInteractions.hpp. Then it should work as ATM.

**Comment by Ghostrider-DbD-** [comment]
Thank you. Your point about the ATMs is well taken, but I think of it as hidding money under your matress. What I had in mind was that the Krypto be added to the inventory of the safe and not be accessible except by interacting with that safe. In that way this feature would be quite different from ATMs.

**Comment by vbawol** [comment]
The dynamic menu https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_config/Configs/CfgActionMenu/CfgActionMenu_target.hpp should be able to do this with a little work. Otherwise the solution that @Ignatz-HeMan posted could work. 

You could also add a check if the vault is locked here https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_code/compile/EPOCH_lootTrash.sqf#L98-L113

with something like:

```
if (!isNull _bankTerminal && !(_bankTerminal getVariable ['EPOCH_Locked',false])) then { 
...
```

**Comment by morgoth0** [comment]
Note, from testing this, HeMan's solution would not work with out dynamic menu changes. There is no EXAMINE option when looking at a locked or unlocked safe.

**Comment by vbawol** [comment]
Will close this for now as it can be added server side if the admin chooses.
