### ISSUE TITLE
Clothings / Weapons sometimes disappear by switching player into unit?!

### ISSUE THREAD

**Issue by Ignatz-HeMan** [EpochModTeam/Epoch#693]
I have noticed, that on our Test-Server (Chernarus) the default Sidepack and Dan are not on respawned Players.
So I made a diag_log for the current clothes at he end of EPOCH_server_loadPlayer.sqf, but in this log, the new player has these clothings.
It seems, that they disappear by switching the player into the new unit.
It is on Altis too, but only very rarely. On Chernarus nearly every time.

Something similar we have noticed by player revive.
The log says, the new player has a primary and secondary weapon in EPOCH_server_revivePlayer, but after revive, he has no weapons.

At first, I thought it was a script failure in revive / load player, but it seems the scripts are okay.
Any idea, what this could be?

**Comment by Ignatz-HeMan** [comment]
Now tested a lot:
On an empty Server (Test-Server), the Weapons disappear in about 6 of 10 revives.
On our Live-Server with 20-30 player, the weapons disappear in about 2 of 10 revives.
So I think, the player switch to fast in the new unit.
Then I changed the EPOCH_server_revivePlayer.sqf, that the code is spawned (not called) and added a short "uisleep 0.2" before the remoteExec.
And voilla... 10 of 10 revives without disappearing weapons on the empty Test-Server.
I am not sure, if you will change it in the stock Epoch files, but we will work with this.
Here the changed EPOCH_server_revivePlayer.sqf:
http://pastebin.com/CwkSCe7q

My next step is to test, if this will also help in the Load Player script on our Chernarus Testserver.
I will give feedback later.
For now it is closed!

**Comment by vbawol** [comment]
It seems like the more A3 optimizes the more our methods do not work. I thought this was addressed with load player, the most reliable thing I found to do was to simply teleport the old player to the new players location just before the switch. This is so they are near each other and the sync seems to work faster this way.

https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_server/compile/epoch_player/EPOCH_server_loadPlayer.sqf#L138

The ideal solution would be something more event driven. We are not doing this with the revive code however the new unit is spawned exactly at the player's death location so I would not think It needed.

The load player code client side also has checks via the FS to make sure the data of the new players object mass has at least propagated before the selectPlayer command is used. Maybe we could do the same with reviving, as I would rather sleep client side than server as the problem is the use of selectPlayer (client side) before the object is fully propagated.
