### ISSUE TITLE
Build: 1.0.0 build(1074) vehicle repair

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#955]
maybe I did something wrong, but at our server vehicle repair and multi gun doesn't work since update to 1.0..
at vehicle repair kit there's no use button
at vehicle repair parts only the craft button and no use aswell
multigun didn't repair a taru even after 130 shots

**Comment by xDrokZ** [comment]
Multigun worked for me in the latest experimental files not tested in 1.0 yet. But i removed the repair vehicle attachment since farming stuff for advanced vehicle repair would be some kind of useless then. 

You would need to disable the advanced vehicle repair and remove Vehicle Repair Kit from blacklistet crafting items to use the old repair system:
 https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_config/Configs/CfgEpochClient.hpp#L193-L207

Not sure about the interactions since they are still defined in CfgItemInteractions.hpp

**Comment by Ignatz-HeMan** [comment]
With Advanced Vehicle Repair activated, the Multigun can only repair not fully damaged vehicle parts.
The whole repair System have been moved into the Space Menu. 
Have a look into cfgepochclient for the settings and hints

**Comment by Tarabass999** [comment]
Thank you for explaining me... that makes sence :-)
