### ISSUE TITLE
Wiping Bases

### ISSUE THREAD

**Issue by TrayMcCloud** [EpochModTeam/Epoch#964]
Hello,

I am on a server and each time the server has a restart it wipes all player bases/safes. This is a problem that only started occurring this morning. It appears that it only happens when the server restarts on its regular cycle. So if an admin does a manual restart it doesn't appear to clear the items.

Thanks

**Comment by ravmustang** [comment]
Without any actual information from the server, it is hard to determine the problem associated.
The first step is to notify the actual server owners.
If they still can't find their problem they can come here, the forums or discord to present their issue and any required info that may help us help them.
These include server RPT files, client RPT files on join when the issue is present and possibly for this situation you mention a peek at their startup routine.

Forums are located here
https://epochmod.com/forum

Discord is here:
https://discord.gg/e2NebE7

**Comment by Ignatz-HeMan** [comment]
Sounds like a server problem, not EPOCH-Mod related.
As @ravmustang sayd, you are welcome to visit the Forum or Discord to get more help (if it is not already fixed).
